coverage:
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: frontend
      paths:
        - src/
      statuses:
        - type: project
          target: auto
          threshold: 1%
