version: '3.9'
services:
  caregiver-dashboard:
    build:
      context: .
      args:
        - REACT_APP_ENVIRONMENT=development
    volumes:
      - './conf/nginx.dev.conf:/etc/nginx/nginx.conf'
    ports:
      - '3000:80'

networks:
  default:
    name: swsp
