name: CI

on: [pull_request] # we want the workflow to trigger on commits to PRs only

jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        run: npm audit --audit-level moderate
        env:
          CI: true
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  build:
    name: Build with Node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 14
          - 16
          - 17
    steps:
      - uses: actions/checkout@v2
      - id: build
        uses: ./.github/actions/build
        with:
          node_version: ${{ matrix.node_version }}

      - run: npm install
      - run: npm run build --if-present
